- name: "[HAPROXY] - role to install haproxy"
  hosts: haproxy
  become: yes
  roles:
    - haproxy_install
  tags:
    - install_haproxy

- name: "[NGINX] - role to install nginx"
  hosts: web1,web2
  become: yes
  roles:
    - role: nginxinc.nginx
  vars:
    nginx_http_template_enable: true
    nginx_http_template:
      default:
        template_file: http/default.conf.j2
        conf_file_name: default.conf
        conf_file_location: /etc/nginx/conf.d/
        servers:
          server1:
            listen:
              listen_localhost:
                # ip: 0.0.0.0
                port: 80
            server_name: localhost
            error_page: /usr/share/nginx/html
            autoindex: false
            web_server:
              locations:
                default:
                  location: /
                  html_file_location: /usr/share/nginx/html
                  html_file_name: index.html
                  autoindex: false
              http_demo_conf: false
  tags:
    - install_nginx
